version: "3.10.2"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=taskList
      - POSTGRES_USER=taskList
      - POSTGRES_PASSWORD=taskList
    volumes:
      #- .:/code
      - taskList_data:/var/lib/postgresql/data
    # - ./onlineshop-volume:/var/lib/postgresql/data
volumes:
  taskList_data:
