# Generated by Django 4.0.3 on 2022-03-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('date_created',)},
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='dateChanged',
            new_name='date_changed',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='dateCreated',
            new_name='date_created',
        ),
    ]
